version: '3'

services:
    blog:
        build: .
        image: blog
        container_name: blog
        ports:
            - 8000:8000
        volumes:
            - static-dir:/blog/static
            - media-dir:/blog/media
    nginx:
        build: ./nginx
        image: nginx
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - static-dir:/blog/static
            - media-dir:/blog/media
        depends_on:
            - blog
volumes:
    static-dir:
    media-dir:
                
