# Generated by Django 3.1.4 on 2020-12-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201211_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authur',
            new_name='author',
        ),
    ]
